from enum import Enum
from typing import Any, Sequence

class dtype(Enum):
    float32: dtype
    float64: dtype
    int32: dtype
    int64: dtype
    uint8: dtype

class Tensor:
    def __init__(self, data: Sequence[float]) -> None: ...
    @staticmethod
    def empty(shape: Sequence[int], dtype: dtype = ...) -> Tensor: ...
    @staticmethod
    def randn(shape: Sequence[int], dtype: dtype = ...) -> Tensor: ...
    @staticmethod
    def zeros(shape: Sequence[int], dtype: dtype = ...) -> Tensor: ...
    @staticmethod
    def ones(shape: Sequence[int], dtype: dtype = ...) -> Tensor: ...
    @property
    def shape(self) -> list[int]: ...
    @property
    def strides(self) -> list[int]: ...
    @property
    def ndim(self) -> int: ...
    @property
    def is_contiguous(self) -> bool: ...
    def __len__(self) -> int: ...
    def transpose(self, dim0: int, dim1: int) -> Tensor: ...
    def t(self) -> Tensor: ...
    def view(self, shape: Sequence[int]) -> Tensor: ...
    def contiguous(self) -> Tensor: ...
    def tolist(self) -> list[Any]: ...
    def __repr__(self) -> str: ...
